import { useState } from 'react'
import type { DocStatus } from '@/lib/types'
import { DOC_TYPE_META, DOC_TYPE_ICON, fieldLabel } from '@/lib/standards'
import { completeness } from '@/lib/agents'
import { useStore } from '@/store/useStore'
import { Badge, Button, Input, Label, Progress, Select, Textarea } from './ui'
import { CriticalityBadge, StatusBadge } from './badges'
import { relativeTime } from '@/lib/utils'
import { Bot, Sparkles, Trash2, X, AlertTriangle } from 'lucide-react'

export function DocEditor({ docId, onClose }: { docId: string; onClose: () => void }) {
  const doc = useStore((s) => s.docs.find((d) => d.id === docId))
  const updateDoc = useStore((s) => s.updateDoc)
  const deleteDoc = useStore((s) => s.deleteDoc)
  const [confirmDelete, setConfirmDelete] = useState(false)

  if (!doc) return null
  const meta = DOC_TYPE_META[doc.type]
  const Icon = DOC_TYPE_ICON[doc.type]
  const c = completeness(doc)

  const setField = (key: string, value: string) =>
    updateDoc(doc.id, { fields: { ...doc.fields, [key]: value } })

  const setSection = (idx: number, value: string) => {
    const sections = doc.sections.map((s, i) => (i === idx ? { ...s, body: value } : s))
    updateDoc(doc.id, { sections })
  }

  const missingSet = new Set(c.missingFields)

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-black/40 animate-fade-in" onClick={onClose}>
      <div
        className="flex h-full w-full max-w-2xl flex-col bg-background shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* header */}
        <div className="flex items-start gap-3 border-b border-border p-5">
          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary">
            <Icon className="h-5 w-5" />
          </div>
          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-2">
              <h2 className="truncate text-lg font-semibold">{doc.title}</h2>
              <StatusBadge status={doc.status} />
              <CriticalityBadge criticality={doc.criticality} />
            </div>
            <p className="mt-0.5 text-xs text-muted-foreground">
              {meta.label} · {doc.environment} · owner {doc.owner} · updated {relativeTime(doc.updatedAt)}
            </p>
            {doc.generatedBy && (
              <Badge tone="accent" className="mt-2">
                <Sparkles className="h-3 w-3" /> Generated by {doc.generatedBy}
              </Badge>
            )}
          </div>
          <button onClick={onClose} className="rounded-lg p-2 text-muted-foreground hover:bg-muted">
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* completeness bar */}
        <div className="border-b border-border bg-muted/40 px-5 py-3">
          <div className="mb-1.5 flex items-center justify-between text-xs">
            <span className="font-medium">Completeness vs. {meta.label} standard</span>
            <span className="font-semibold">{c.score}%</span>
          </div>
          <Progress
            value={c.score}
            barClassName={c.score >= 75 ? 'bg-success' : c.score >= 50 ? 'bg-warning' : 'bg-danger'}
          />
          {(c.missingFields.length > 0 || c.missingSections.length > 0) && (
            <div className="mt-2 flex items-start gap-1.5 text-[11px] text-muted-foreground">
              <AlertTriangle className="mt-px h-3.5 w-3.5 shrink-0 text-warning" />
              <span>
                Missing:{' '}
                {[...c.missingFields.map(fieldLabel), ...c.missingSections].join(', ')}
              </span>
            </div>
          )}
        </div>

        <div className="flex-1 space-y-6 overflow-y-auto p-5">
          {/* metadata */}
          <section>
            <h3 className="mb-3 text-sm font-semibold">Properties</h3>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label>Status</Label>
                <Select
                  value={doc.status}
                  onChange={(e) => updateDoc(doc.id, { status: e.target.value as DocStatus })}
                >
                  <option value="draft">Draft</option>
                  <option value="review">In review</option>
                  <option value="published">Published</option>
                </Select>
              </div>
              <div>
                <Label>Owner</Label>
                <Input value={doc.owner} onChange={(e) => updateDoc(doc.id, { owner: e.target.value })} />
              </div>
            </div>
          </section>

          {/* structured fields */}
          <section>
            <h3 className="mb-3 text-sm font-semibold">Key facts</h3>
            <div className="grid grid-cols-2 gap-3">
              {meta.requiredFields.map((key) => (
                <div key={key}>
                  <Label className={missingSet.has(key) ? 'text-danger' : ''}>
                    {fieldLabel(key)} {missingSet.has(key) && '*'}
                  </Label>
                  <Input
                    value={doc.fields[key] ?? ''}
                    onChange={(e) => setField(key, e.target.value)}
                    placeholder="—"
                    className={missingSet.has(key) ? 'border-danger/50' : ''}
                  />
                </div>
              ))}
            </div>
          </section>

          {/* sections */}
          <section className="space-y-4">
            <h3 className="text-sm font-semibold">Documentation sections</h3>
            {meta.requiredSections.map((heading) => {
              const idx = doc.sections.findIndex((s) => s.heading.toLowerCase() === heading.toLowerCase())
              const body = idx >= 0 ? doc.sections[idx].body : ''
              const missing = c.missingSections.includes(heading)
              return (
                <div key={heading}>
                  <Label className={missing ? 'text-danger' : ''}>
                    {heading} {missing && '*'}
                  </Label>
                  <Textarea
                    rows={3}
                    value={body}
                    placeholder={`Document ${heading.toLowerCase()}…`}
                    className={missing ? 'border-danger/50' : ''}
                    onChange={(e) => {
                      if (idx >= 0) setSection(idx, e.target.value)
                      else
                        updateDoc(doc.id, {
                          sections: [...doc.sections, { heading, body: e.target.value }],
                        })
                    }}
                  />
                </div>
              )
            })}
          </section>
        </div>

        {/* footer */}
        <div className="flex items-center justify-between border-t border-border p-4">
          {confirmDelete ? (
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground">Delete this document?</span>
              <Button
                size="sm"
                variant="danger"
                onClick={() => {
                  deleteDoc(doc.id)
                  onClose()
                }}
              >
                Confirm
              </Button>
              <Button size="sm" variant="ghost" onClick={() => setConfirmDelete(false)}>
                Cancel
              </Button>
            </div>
          ) : (
            <Button size="sm" variant="ghost" onClick={() => setConfirmDelete(true)}>
              <Trash2 className="h-4 w-4" /> Delete
            </Button>
          )}
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <Bot className="h-3.5 w-3.5" /> Changes save automatically
          </div>
        </div>
      </div>
    </div>
  )
}
