import { getSkillById, agentSkills } from '../skills/skillDefinitions.js';

export interface AgentRunInput {
  skillId: string;
  inputs: Record<string, string>;
  tenantId?: string;
}

export interface AgentFinding {
  severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
  section: string;
  message: string;
  recommendation: string;
}

export interface AgentRunResult {
  skillId: string;
  skillName: string;
  status: 'completed' | 'failed';
  outputType: string;
  title: string;
  content: string;
  findings?: AgentFinding[];
  checklist?: { item: string; status: 'pass' | 'fail' | 'review'; notes: string }[];
  metadata: {
    executedAt: string;
    durationMs: number;
    sectionsGenerated: number;
  };
}

const NIST_800_123_REQUIRED = [
  { section: 'Basis-Informationen', keywords: ['hostname', 'ip', 'standort', 'verantwortlich'] },
  { section: 'Hardware', keywords: ['cpu', 'ram', 'speicher', 'hardware'] },
  { section: 'Software', keywords: ['betriebssystem', 'os', 'version', 'patch', 'software'] },
  { section: 'Dienste', keywords: ['dienst', 'service', 'port', 'rolle'] },
  { section: 'Netzwerk', keywords: ['netzwerk', 'vlan', 'subnet', 'gateway', 'dns'] },
  { section: 'Sicherheit', keywords: ['firewall', 'sicherheit', 'security', 'zugriff', 'verschlüsselung'] },
  { section: 'Backup', keywords: ['backup', 'wiederherstellung', 'recovery', 'rto', 'rpo'] },
  { section: 'Monitoring', keywords: ['monitoring', 'alert', 'überwachung', 'log'] },
];

function runGapAnalysis(inputs: Record<string, string>): AgentRunResult {
  const content = (inputs.documentContent || '').toLowerCase();
  const findings: AgentFinding[] = [];

  for (const req of NIST_800_123_REQUIRED) {
    const found = req.keywords.some((kw) => content.includes(kw));
    if (!found) {
      findings.push({
        severity: req.section === 'Sicherheit' || req.section === 'Backup' ? 'high' : 'medium',
        section: req.section,
        message: `Missing or insufficient coverage of "${req.section}"`,
        recommendation: `Add a dedicated section covering ${req.section.toLowerCase()} with required details per ${inputs.standard || 'NIST SP 800-123'}.`,
      });
    }
  }

  const coverage = Math.round(((NIST_800_123_REQUIRED.length - findings.length) / NIST_800_123_REQUIRED.length) * 100);

  return {
    skillId: 'gap-analysis',
    skillName: 'Documentation Gap Analysis',
    status: 'completed',
    outputType: 'findings',
    title: `Gap Analysis: ${inputs.documentTitle}`,
    content: `## Gap Analysis Report\n\n**Document:** ${inputs.documentTitle}\n**Standard:** ${inputs.standard}\n**Coverage Score:** ${coverage}%\n\n${findings.length === 0 ? '✅ No critical gaps found. Documentation meets standard requirements.' : `⚠️ ${findings.length} gap(s) identified.`}`,
    findings,
    metadata: { executedAt: new Date().toISOString(), durationMs: 0, sectionsGenerated: findings.length },
  };
}

function runServerDoc(inputs: Record<string, string>): AgentRunResult {
  const now = new Date().toLocaleDateString('de-DE');
  const content = `<div class="trust-doc">
<h1>Server-Dokumentation: ${inputs.hostname}</h1>
<p><em>Generated by Trust Doc Agent · ${now}</em></p>

<h2>1. Basis-Informationen</h2>
<table>
<tr><td><strong>Hostname</strong></td><td>${inputs.hostname}</td></tr>
<tr><td><strong>IP-Adresse</strong></td><td>${inputs.ipAddress}</td></tr>
<tr><td><strong>Standort</strong></td><td>${inputs.location || '—'}</td></tr>
<tr><td><strong>Umgebung</strong></td><td>${inputs.environment}</td></tr>
<tr><td><strong>Verantwortlicher</strong></td><td>${inputs.owner || '—'}</td></tr>
</table>

<h2>2. Software & Betriebssystem</h2>
<p><strong>Betriebssystem:</strong> ${inputs.operatingSystem}</p>

<h2>3. Dienste & Rollen</h2>
<p>${inputs.serverRole || 'No roles specified — please complete this section.'}</p>

<h2>4. Sicherheit</h2>
<p><em>⚠️ Review required: Document firewall rules, access controls, and patch status.</em></p>

<h2>5. Backup & Recovery</h2>
<p><em>⚠️ Review required: Document backup schedule, retention, RTO/RPO.</em></p>

<h2>6. Monitoring</h2>
<p><em>⚠️ Review required: Document monitoring tools and alert thresholds.</em></p>
</div>`;

  return {
    skillId: 'draft-server-doc',
    skillName: 'Server Documentation',
    status: 'completed',
    outputType: 'document',
    title: `Server Documentation — ${inputs.hostname}`,
    content,
    metadata: { executedAt: new Date().toISOString(), durationMs: 0, sectionsGenerated: 6 },
  };
}

function runNetworkDoc(inputs: Record<string, string>): AgentRunResult {
  const now = new Date().toLocaleDateString('de-DE');
  const content = `<div class="trust-doc">
<h1>Network Documentation: ${inputs.networkName}</h1>
<p><em>Generated by Trust Doc Agent · ${now}</em></p>

<h2>1. Network Overview</h2>
<p><strong>Network:</strong> ${inputs.networkName}</p>

<h2>2. Subnets & VLANs</h2>
<pre>${inputs.subnets}</pre>

<h2>3. Core Infrastructure</h2>
<pre>${inputs.coreDevices || 'Not specified'}</pre>

<h2>4. WAN / Internet Connectivity</h2>
<p>${inputs.wanConnections || 'Not specified'}</p>

<h2>5. DNS Configuration</h2>
<p><strong>DNS Servers:</strong> ${inputs.dnsServers || 'Not specified'}</p>

<h2>6. Security Zones</h2>
<p><em>⚠️ Review required: Document DMZ, internal zones, and firewall policies.</em></p>
</div>`;

  return {
    skillId: 'network-topology-doc',
    skillName: 'Network Topology Documentation',
    status: 'completed',
    outputType: 'document',
    title: `Network Documentation — ${inputs.networkName}`,
    content,
    metadata: { executedAt: new Date().toISOString(), durationMs: 0, sectionsGenerated: 6 },
  };
}

function runBackupProcedure(inputs: Record<string, string>): AgentRunResult {
  const content = `<div class="trust-doc">
<h1>Backup & Recovery Procedure: ${inputs.systemName}</h1>

<h2>1. Scope</h2>
<p>This procedure covers backup and recovery operations for <strong>${inputs.systemName}</strong>.</p>

<h2>2. Backup Solution</h2>
<p><strong>Tool:</strong> ${inputs.backupTool}</p>

<h2>3. Schedule</h2>
<p>${inputs.schedule}</p>

<h2>4. Retention Policy</h2>
<p>${inputs.retention || 'To be defined'}</p>

<h2>5. Recovery Objectives</h2>
<table>
<tr><td><strong>RTO</strong></td><td>${inputs.rto || 'TBD'}</td></tr>
<tr><td><strong>RPO</strong></td><td>${inputs.rpo || 'TBD'}</td></tr>
</table>

<h2>6. Recovery Steps</h2>
<ol>
<li>Identify failure scope and impact</li>
<li>Notify stakeholders per escalation matrix</li>
<li>Initiate recovery from latest verified backup</li>
<li>Validate data integrity post-recovery</li>
<li>Document incident and update runbook</li>
</ol>
</div>`;

  return {
    skillId: 'backup-procedure',
    skillName: 'Backup & Recovery Procedure',
    status: 'completed',
    outputType: 'document',
    title: `Backup Procedure — ${inputs.systemName}`,
    content,
    metadata: { executedAt: new Date().toISOString(), durationMs: 0, sectionsGenerated: 6 },
  };
}

function runSecurityChecklist(inputs: Record<string, string>): AgentRunResult {
  const scope = inputs.scope || 'server';
  const items: Record<string, string[]> = {
    server: [
      'OS patches applied within 30 days',
      'Unnecessary services disabled',
      'Firewall rules documented and reviewed',
      'Admin accounts use MFA',
      'Audit logging enabled',
      'Antivirus/EDR agent running',
      'Disk encryption enabled',
      'Backup verified within 7 days',
    ],
    network: [
      'Network segmentation implemented',
      'Default credentials changed on all devices',
      'SNMP v3 or disabled',
      'Unused ports disabled',
      'IDS/IPS rules up to date',
      'VPN access requires MFA',
      'Network diagrams current',
      'Change management process followed',
    ],
    endpoint: [
      'Endpoint protection deployed',
      'USB port policies enforced',
      'Screen lock after 5 minutes',
      'Local admin rights restricted',
      'Software whitelist enforced',
      'Full disk encryption active',
    ],
    cloud: [
      'IAM roles follow least privilege',
      'MFA enforced for all users',
      'Cloud audit logging enabled',
      'Data encryption at rest configured',
      'Network security groups reviewed',
      'Backup and DR tested quarterly',
    ],
  };

  const checklist = (items[scope] || items.server).map((item) => ({
    item,
    status: 'review' as const,
    notes: '',
  }));

  return {
    skillId: 'security-audit-checklist',
    skillName: 'Security Audit Checklist',
    status: 'completed',
    outputType: 'checklist',
    title: `Security Audit — ${scope.charAt(0).toUpperCase() + scope.slice(1)}`,
    content: `Security audit checklist for ${scope} scope. Review each item and mark pass/fail.`,
    checklist,
    metadata: { executedAt: new Date().toISOString(), durationMs: 0, sectionsGenerated: checklist.length },
  };
}

function runIncidentRunbook(inputs: Record<string, string>): AgentRunResult {
  const type = inputs.incidentType || 'server-down';
  const labels: Record<string, string> = {
    'server-down': 'Server Unreachable',
    'network-outage': 'Network Outage',
    'security-breach': 'Security Incident',
    'data-loss': 'Data Loss / Corruption',
    'service-degradation': 'Service Degradation',
  };

  const content = `<div class="trust-doc">
<h1>Incident Runbook: ${labels[type]}</h1>
<p><strong>Severity:</strong> ${inputs.severity || 'High (P2)'}</p>

<h2>1. Initial Response (0–15 min)</h2>
<ol>
<li>Acknowledge alert and create incident ticket</li>
<li>Assess scope: ${inputs.affectedSystems}</li>
<li>Notify on-call engineer and team lead</li>
<li>Begin timeline documentation</li>
</ol>

<h2>2. Investigation (15–60 min)</h2>
<ol>
<li>Check monitoring dashboards and logs</li>
<li>Verify recent changes (change log review)</li>
<li>Isolate affected systems if security-related</li>
<li>Collect diagnostic data</li>
</ol>

<h2>3. Resolution</h2>
<ol>
<li>Apply fix or initiate failover/recovery</li>
<li>Validate service restoration</li>
<li>Monitor for recurrence (30 min)</li>
</ol>

<h2>4. Escalation Contacts</h2>
<pre>${inputs.escalationContacts || 'Define escalation contacts'}</pre>

<h2>5. Post-Incident</h2>
<ol>
<li>Complete incident report within 24 hours</li>
<li>Schedule post-mortem if P1/P2</li>
<li>Update documentation and runbook</li>
</ol>
</div>`;

  return {
    skillId: 'incident-runbook',
    skillName: 'Incident Response Runbook',
    status: 'completed',
    outputType: 'document',
    title: `Runbook: ${labels[type]}`,
    content,
    metadata: { executedAt: new Date().toISOString(), durationMs: 0, sectionsGenerated: 5 },
  };
}

const skillExecutors: Record<string, (inputs: Record<string, string>) => AgentRunResult> = {
  'draft-server-doc': runServerDoc,
  'gap-analysis': runGapAnalysis,
  'network-topology-doc': runNetworkDoc,
  'backup-procedure': runBackupProcedure,
  'security-audit-checklist': runSecurityChecklist,
  'incident-runbook': runIncidentRunbook,
};

export async function runAgentSkill(input: AgentRunInput): Promise<AgentRunResult> {
  const start = Date.now();
  const skill = getSkillById(input.skillId);

  if (!skill) {
    throw new Error(`Unknown skill: ${input.skillId}`);
  }

  for (const field of skill.fields) {
    if (field.required && !input.inputs[field.key]?.trim()) {
      throw new Error(`Required field missing: ${field.label}`);
    }
  }

  const executor = skillExecutors[input.skillId];
  if (!executor) {
    throw new Error(`Skill executor not implemented: ${input.skillId}`);
  }

  const result = executor(input.inputs);
  result.metadata.durationMs = Date.now() - start;
  return result;
}

export function listSkills() {
  return agentSkills;
}
