import {
  Server,
  Network,
  Workflow,
  ShieldCheck,
  DatabaseBackup,
  ScanSearch,
  type LucideIcon,
} from 'lucide-react'
import type { Asset, DocCategory, TrustDocument } from '../types'

export interface AgentField {
  id: string
  label: string
  type: 'text' | 'textarea' | 'select'
  placeholder?: string
  options?: string[]
  required?: boolean
  defaultValue?: string
  help?: string
}

export interface AgentContext {
  assets: Asset[]
  documents: TrustDocument[]
}

export interface GeneratedDoc {
  title: string
  category: DocCategory
  tags: string[]
  content: string
}

export interface AgentSkill {
  id: string
  name: string
  tagline: string
  description: string
  icon: LucideIcon
  category: DocCategory
  accent: string
  fields: AgentField[]
  plan: string[]
  generate: (inputs: Record<string, string>, ctx: AgentContext) => GeneratedDoc
}

const today = () => new Date().toISOString().slice(0, 10)

const val = (inputs: Record<string, string>, id: string, fallback = '—') => {
  const v = (inputs[id] || '').trim()
  return v.length ? v : fallback
}

const bullets = (raw: string, fallback: string[]) => {
  const items = raw
    .split(/[\n,]/)
    .map((s) => s.trim())
    .filter(Boolean)
  const list = items.length ? items : fallback
  return list.map((i) => `- ${i}`).join('\n')
}

export const agentSkills: AgentSkill[] = [
  {
    id: 'server-runbook',
    name: 'Server Documentation & Runbook',
    tagline: 'Full operational runbook for a single server.',
    description:
      'Produces a standardized server document: overview, specifications, services, networking, monitoring, maintenance and a step-by-step recovery procedure.',
    icon: Server,
    category: 'Server',
    accent: 'bg-blue-500/10 text-blue-500',
    plan: [
      'Collecting server attributes and role',
      'Structuring specification & service inventory',
      'Drafting monitoring and maintenance sections',
      'Writing recovery & escalation procedure',
      'Formatting NIST-aligned runbook',
    ],
    fields: [
      { id: 'hostname', label: 'Hostname', type: 'text', placeholder: 'APP-PROD-02', required: true },
      {
        id: 'role',
        label: 'Primary Role',
        type: 'text',
        placeholder: 'Application web tier',
        required: true,
      },
      {
        id: 'environment',
        label: 'Environment',
        type: 'select',
        options: ['Production', 'Staging', 'Development', 'DR'],
        defaultValue: 'Production',
      },
      {
        id: 'os',
        label: 'Operating System',
        type: 'text',
        placeholder: 'Ubuntu Server 24.04 LTS',
      },
      { id: 'ip', label: 'IP Address', type: 'text', placeholder: '10.10.2.22' },
      { id: 'owner', label: 'Owning Team', type: 'text', placeholder: 'Application Team' },
      {
        id: 'services',
        label: 'Hosted Services',
        type: 'textarea',
        placeholder: 'nginx, Node.js app, redis-cache',
        help: 'Comma or line separated. The agent expands each into a documented entry.',
      },
    ],
    generate: (inputs) => {
      const host = val(inputs, 'hostname', 'SERVER')
      const role = val(inputs, 'role', 'General-purpose server')
      const env = val(inputs, 'environment', 'Production')
      const os = val(inputs, 'os', 'Linux')
      const ip = val(inputs, 'ip')
      const owner = val(inputs, 'owner', 'Platform Team')
      const services = bullets(inputs.services || '', [
        'Base operating system & security agent',
        'Monitoring agent',
      ])
      return {
        title: `${host} — ${role} Runbook`,
        category: 'Server',
        tags: ['server', 'runbook', env.toLowerCase()],
        content: `# ${host} — ${role} Runbook

> Generated by the TrustDoc Agent on ${today()}. Review before publishing.

## 1. Overview
${host} is a **${role.toLowerCase()}** operating in the **${env}** environment. This runbook captures everything required to operate, maintain and recover the system.

| Property | Value |
| --- | --- |
| Hostname | ${host} |
| Role | ${role} |
| Environment | ${env} |
| IP Address | ${ip} |
| Operating System | ${os} |
| Owner | ${owner} |
| Last reviewed | ${today()} |

## 2. Hosted Services
${services}

## 3. Networking
- Management access via the management VLAN only.
- Inbound firewall rules limited to the documented service ports.
- DNS records validated against the authoritative zone.

## 4. Monitoring & Alerting
| Signal | Threshold | Action |
| --- | --- | --- |
| CPU | > 85% for 10 min | Investigate top processes |
| Memory | > 90% | Check for leaks / scale |
| Disk | > 80% | Reclaim space, extend volume |
| Service health | Down | Page on-call (${owner}) |

## 5. Maintenance
- **Patch window:** monthly, outside business hours.
- Take a snapshot/backup before any change.
- Record all changes in the change log below.

## 6. Recovery Procedure
1. Confirm the scope of the incident and notify ${owner}.
2. Validate dependencies (network, storage, upstream services) are healthy.
3. Restore from the most recent verified backup if data loss occurred.
4. Restart hosted services in dependency order.
5. Run post-recovery validation and document the timeline.

## 7. Change Log
| Date | Author | Change |
| --- | --- | --- |
| ${today()} | TrustDoc Agent | Initial documentation generated |`,
      }
    },
  },

  {
    id: 'network-device',
    name: 'Network Device Documentation',
    tagline: 'Document firewalls, switches and routers consistently.',
    description:
      'Generates a network device document with interface inventory, VLAN/zone mapping, high-availability details and a configuration baseline.',
    icon: Network,
    category: 'Network',
    accent: 'bg-cyan-500/10 text-cyan-500',
    plan: [
      'Identifying device class and vendor',
      'Mapping interfaces and zones',
      'Documenting high-availability design',
      'Capturing configuration baseline',
      'Formatting network document',
    ],
    fields: [
      { id: 'name', label: 'Device Name', type: 'text', placeholder: 'SW-DIST-02', required: true },
      {
        id: 'class',
        label: 'Device Class',
        type: 'select',
        options: ['Firewall', 'Switch', 'Router', 'Load Balancer'],
        defaultValue: 'Switch',
      },
      { id: 'vendor', label: 'Vendor / OS', type: 'text', placeholder: 'Cisco IOS-XE 17.9' },
      { id: 'mgmtIp', label: 'Management IP', type: 'text', placeholder: '10.10.0.3' },
      {
        id: 'zones',
        label: 'Zones / VLANs',
        type: 'textarea',
        placeholder: 'Management 10.10.1.0/24, Servers 10.10.2.0/24',
      },
    ],
    generate: (inputs) => {
      const name = val(inputs, 'name', 'NET-DEVICE')
      const cls = val(inputs, 'class', 'Switch')
      const vendor = val(inputs, 'vendor', 'Vendor OS')
      const mgmt = val(inputs, 'mgmtIp')
      const zones = bullets(inputs.zones || '', ['Management', 'Servers', 'Backup'])
      return {
        title: `${name} — ${cls} Documentation`,
        category: 'Network',
        tags: ['network', cls.toLowerCase(), 'configuration'],
        content: `# ${name} — ${cls} Documentation

> Generated by the TrustDoc Agent on ${today()}.

## Overview
${name} is a **${cls.toLowerCase()}** running **${vendor}**, central to the production network fabric.

| Property | Value |
| --- | --- |
| Device | ${name} |
| Class | ${cls} |
| Vendor / OS | ${vendor} |
| Management IP | ${mgmt} |

## Zones / VLANs
${zones}

## High Availability
- Redundant pair recommended for ${cls.toLowerCase()} roles.
- Failover tested quarterly and results recorded.

## Configuration Baseline
- Management plane reachable only from the management VLAN.
- SSH only, with key-based auth and an idle timeout.
- Centralized logging (syslog) and NTP configured.
- Running configuration backed up after every approved change.

## Operational Checks
1. Confirm uplinks and port-channels are up.
2. Verify spanning-tree / routing convergence.
3. Validate ACLs against the documented policy.`,
      }
    },
  },

  {
    id: 'infra-overview',
    name: 'Infrastructure Topology Overview',
    tagline: 'A bird’s-eye view assembled from your inventory.',
    description:
      'Builds a high-level infrastructure overview directly from the assets currently tracked in TrustDoc, grouped by environment.',
    icon: Workflow,
    category: 'Infrastructure',
    accent: 'bg-violet-500/10 text-violet-500',
    plan: [
      'Reading the live asset inventory',
      'Grouping assets by environment',
      'Summarizing platform building blocks',
      'Highlighting dependencies',
      'Formatting topology overview',
    ],
    fields: [
      {
        id: 'siteName',
        label: 'Site / Scope Name',
        type: 'text',
        placeholder: 'Frankfurt Data Center',
        required: true,
      },
    ],
    generate: (inputs, ctx) => {
      const site = val(inputs, 'siteName', 'Primary Site')
      const byEnv = ctx.assets.reduce<Record<string, Asset[]>>((acc, a) => {
        ;(acc[a.environment] ||= []).push(a)
        return acc
      }, {})
      const sections = Object.entries(byEnv)
        .map(([env, assets]) => {
          const rows = assets
            .map((a) => `| ${a.name} | ${a.type} | ${a.ip} | ${a.status} |`)
            .join('\n')
          return `### ${env}\n\n| Asset | Type | IP | Status |\n| --- | --- | --- | --- |\n${rows}`
        })
        .join('\n\n')
      return {
        title: `${site} — Infrastructure Overview`,
        category: 'Infrastructure',
        tags: ['infrastructure', 'topology', 'overview'],
        content: `# ${site} — Infrastructure Overview

> Generated by the TrustDoc Agent on ${today()} from ${ctx.assets.length} tracked asset(s).

## Summary
This overview reflects the current inventory tracked in TrustDoc, grouped by environment. Keep it current by re-running the agent after infrastructure changes.

## Assets by Environment
${sections || '_No assets are currently tracked._'}

## Dependencies & Notes
- Production workloads depend on the core network (firewall, core switch) and the virtualization cluster.
- Backup repository must reach all tier-1 systems for protection to be valid.
- Review this overview at least quarterly or after major change events.`,
      }
    },
  },

  {
    id: 'backup-dr',
    name: 'Backup & DR Plan',
    tagline: 'RPO/RTO-driven backup and recovery plan.',
    description:
      'Creates a disaster-recovery plan with objectives, a backup schedule, restore procedures and a testing cadence.',
    icon: DatabaseBackup,
    category: 'Backup & DR',
    accent: 'bg-emerald-500/10 text-emerald-500',
    plan: [
      'Setting recovery objectives',
      'Building the backup schedule',
      'Drafting restore procedures',
      'Defining the test cadence',
      'Formatting DR plan',
    ],
    fields: [
      { id: 'scope', label: 'Scope', type: 'text', placeholder: 'Tier-1 production systems', required: true },
      { id: 'rpo', label: 'Target RPO', type: 'text', placeholder: '1 hour', defaultValue: '1 hour' },
      { id: 'rto', label: 'Target RTO', type: 'text', placeholder: '4 hours', defaultValue: '4 hours' },
      { id: 'tool', label: 'Backup Tooling', type: 'text', placeholder: 'Veeam Backup & Replication 12' },
    ],
    generate: (inputs) => {
      const scope = val(inputs, 'scope', 'Production systems')
      const rpo = val(inputs, 'rpo', '1 hour')
      const rto = val(inputs, 'rto', '4 hours')
      const tool = val(inputs, 'tool', 'the backup platform')
      return {
        title: `Backup & DR Plan — ${scope}`,
        category: 'Backup & DR',
        tags: ['backup', 'dr', 'rpo', 'rto'],
        content: `# Backup & DR Plan — ${scope}

> Generated by the TrustDoc Agent on ${today()}.

## 1. Objectives
- **Scope:** ${scope}
- **RPO (max data loss):** ${rpo}
- **RTO (max downtime):** ${rto}
- **Tooling:** ${tool}

## 2. Backup Schedule
| Workload | Frequency | Retention | Offsite |
| --- | --- | --- | --- |
| Domain Controllers | Daily | 30 days | Yes |
| Databases | Hourly log + daily full | 35 days | Yes |
| Application servers | Daily | 30 days | Yes |
| File services | Daily | 90 days | Yes |

## 3. Restore Procedure
1. Declare the incident and assemble the recovery team.
2. Identify the most recent verified restore point within ${rpo}.
3. Restore to isolated network, validate integrity.
4. Cut over and confirm service health within ${rto}.
5. Document the recovery timeline and lessons learned.

## 4. Testing
- Monthly restore drills against an isolated environment.
- Annual full DR failover exercise.
- Every restore test is logged with success/failure and duration.`,
      }
    },
  },

  {
    id: 'security-baseline',
    name: 'Security Hardening Baseline',
    tagline: 'A control baseline aligned to common frameworks.',
    description:
      'Generates a hardening baseline covering identity, network, logging, patching and data protection controls for a system or system class.',
    icon: ShieldCheck,
    category: 'Security',
    accent: 'bg-amber-500/10 text-amber-500',
    plan: [
      'Selecting applicable control families',
      'Mapping identity & access controls',
      'Defining network & logging controls',
      'Adding patch & data-protection controls',
      'Formatting hardening baseline',
    ],
    fields: [
      {
        id: 'system',
        label: 'System / Class',
        type: 'text',
        placeholder: 'Windows Server 2022 fleet',
        required: true,
      },
      {
        id: 'framework',
        label: 'Reference Framework',
        type: 'select',
        options: ['CIS Benchmarks', 'NIST 800-53', 'ISO 27001', 'BSI Grundschutz'],
        defaultValue: 'CIS Benchmarks',
      },
    ],
    generate: (inputs) => {
      const system = val(inputs, 'system', 'Target system')
      const fw = val(inputs, 'framework', 'CIS Benchmarks')
      return {
        title: `Security Hardening Baseline — ${system}`,
        category: 'Security',
        tags: ['security', 'hardening', 'compliance'],
        content: `# Security Hardening Baseline — ${system}

> Generated by the TrustDoc Agent on ${today()}. Reference framework: **${fw}**.

## Identity & Access
- Enforce MFA for all administrative access.
- Apply least-privilege role assignments; review quarterly.
- Disable or rename default accounts.

## Network
- Default-deny inbound; allow only documented ports.
- Segment management traffic onto a dedicated VLAN.
- Terminate remote access through a hardened bastion/VPN.

## Logging & Monitoring
- Forward security logs to the central SIEM.
- Retain logs per policy (minimum 90 days online).
- Alert on privileged actions and authentication anomalies.

## Patch & Vulnerability Management
- Critical patches applied within the defined SLA.
- Monthly authenticated vulnerability scans.
- Track remediation to closure.

## Data Protection
- Encrypt data at rest and in transit.
- Validate backups (see the Backup & DR plan).
- Classify and label sensitive data.

## Control Mapping (${fw})
| Domain | Status | Evidence |
| --- | --- | --- |
| Identity | Planned | — |
| Network | Planned | — |
| Logging | Planned | — |
| Patching | Planned | — |
| Data | Planned | — |`,
      }
    },
  },

  {
    id: 'gap-audit',
    name: 'Documentation Gap Audit',
    tagline: 'Find undocumented assets and stale docs.',
    description:
      'The agent scans your inventory and library to surface assets without documentation, outdated documents and overall coverage — no input required.',
    icon: ScanSearch,
    category: 'Runbook',
    accent: 'bg-rose-500/10 text-rose-500',
    plan: [
      'Indexing the asset inventory',
      'Cross-referencing the documentation library',
      'Detecting undocumented assets',
      'Flagging outdated documents',
      'Compiling the audit report',
    ],
    fields: [],
    generate: (_inputs, ctx) => {
      const documentedAssetIds = new Set(
        ctx.documents.map((d) => d.linkedAssetId).filter(Boolean) as string[]
      )
      const undocumented = ctx.assets.filter((a) => !documentedAssetIds.has(a.id))
      const outdated = ctx.documents.filter((d) => d.status === 'Outdated')
      const coverage = ctx.assets.length
        ? Math.round(((ctx.assets.length - undocumented.length) / ctx.assets.length) * 100)
        : 100

      const undocumentedList = undocumented.length
        ? undocumented.map((a) => `- **${a.name}** (${a.type}, ${a.environment}) — no linked document`).join('\n')
        : '- None — every tracked asset has documentation.'
      const outdatedList = outdated.length
        ? outdated.map((d) => `- **${d.title}** — last updated ${d.updatedAt.slice(0, 10)}`).join('\n')
        : '- None — no documents are flagged as outdated.'

      return {
        title: `Documentation Gap Audit — ${today()}`,
        category: 'Runbook',
        tags: ['audit', 'coverage', 'quality'],
        content: `# Documentation Gap Audit

> Generated by the TrustDoc Agent on ${today()}.

## Coverage Summary
| Metric | Value |
| --- | --- |
| Tracked assets | ${ctx.assets.length} |
| Documented assets | ${ctx.assets.length - undocumented.length} |
| Documentation coverage | ${coverage}% |
| Outdated documents | ${outdated.length} |

## Undocumented Assets
${undocumentedList}

## Outdated Documents
${outdatedList}

## Recommended Actions
1. Run the **Server** or **Network Device** skill for each undocumented asset.
2. Review and refresh outdated documents, then set their status to *Published*.
3. Re-run this audit after remediation to confirm coverage improved.`,
      }
    },
  },
]

export function getSkill(id: string) {
  return agentSkills.find((s) => s.id === id)
}
